////
The following is the approved connector release notes template for documenting MuleSoft Supported Connectors.
////

= Thru MFT Connector Release Notes
////
[<System_Name>: The system the connector connects to, at the other end of the mule runtime, i.e. SalesForce, Workday Financials]
////
:keywords: Thru, MFT


Thru MFT Connector for MuleSoft Anypoint Studio is an out-of-the-box connector to implement file exchange with external and internal organizations for your Mule Flows. The connector enables Thru MFT as a service (MFTaaS) cloud platform to a solution based on Mule ESB. Thru MFT cloud service implements the following features for the MuleSoft - based enterprise solutions:

- Reliable file exchange between organizations and Mule flows with audit, alerts and business continuity
- Partner Management with subscriptions, self - management, reusable endpoints and support, out of the box protocol and API connectors.
- Centralized system of record  
- Monitoring and control of all file transfers across all organizations and partners using real-time end-to-end processing dashboards
- Scalable and secure REST API for Mule and other connectors
- Developer environment

link:user-manual.adoc[Thru MFT Connector User Guide]
////
Points to the docs.mulesoft pages for documentation on the functional aspects of the connector. e.g.: link:/mule-user-guide/v/3.7/microsoft-sharepoint-2013-connector[Microsoft SharePoint 2013 Connector]
////

== Thru MFT 2.0.2 - Oct 2020
////
<Release_date> : The date on which the connector is released (not when the notes are written, mind you)
////

=== Version 2.0.2 Compatibility

Thru MFT Connector 2.0.2 is compatible with all currently deployed versions of Thru MFT service.

[width="100%", cols=",", options="header"]
|===
|Software |Version
|Mule Runtime |4.0
|Thru MFT Service |4.84
|===

=== Version 2.0.2:  Changes in this Release
=== New Features
- Added web proxy support
- Configurable HTTP timeout
- Changed logging at the INFO level to only show messages for processed files. I.e. logging for filePickup cron job executions where no file is picked up have been removed.
- Changed logging at the DEBUG level to log all entry and exist point executions.

=== Defects Fixed
- Fixed an issue with the fileDropOff operation where the HTTP threads were not being stopped.

== Thru MFT 2.0.1 - February 2019
////
<Connector_Version> : Describes the connector version, such as “V2013”, “V4.0”, “V4.0.1-HF2” or whatever used for release]
<Release_date> : The date on which the connector is released (not when the notes are written, mind you)
////

=== Version 2.0.1 Compatibility

Thru MFT Connector 2.0.1 is compatible with all currently deployed versions of Thru MFT service.

[width="100%", cols=",", options="header"]
|===
|Software |Version
|Mule Runtime |4.0
|Thru MFT Service |4.84
|===


=== Version 2.0.1:   Changes in this Release

- Change logging level of HTTP messages 200 and 204 and few other from INFO to DEBUG
- Change logging level for message '...Content-Disposition..' from INFO to DEBUG
- Suppress debug message: Method returns InputStream equal to null
- Rename the field 'File Code' to 'Related Pickup File Code'


== Thru MFT 2.0.0 - June 1 2018
////
<Connector_Version> : Describes the connector version, such as “V2013”, “V4.0”, “V4.0.1-HF2” or whatever used for release]
<Release_date> : The date on which the connector is released (not when the notes are written, mind you)
////

=== Version 2.0.0 Compatibility

Thru MFT Connector 2.0.0 is the first version for Mule 4 and is not compatible with the Mule 3 environment. The version is compatible with currently deployed version of Thru MFT service.

[width="100%", cols=",", options="header"]
|===
|Software |Version
|Mule Runtime |4.0
|Thru MFT Service |4.84
|===

////

If you’re currently using a connector version <old_connector_version_2> this connector is not compatible. Don’t upgrade to this connector unless you are sure you do the following:

- <step_3>
- <step_4>

<Step_1 to N should be clear instructions that pertain to the migration path from one connector to the other.

//Examples might include

//- Specifying which version of the runtime is needed for the new connector
//- Changes in the version of the connected systems to be able to work
//- When the connector suffers structural changes (i.e monolythic connectors now many update sites) we should also inform the split and why and how to update from one to //the other.
//- Specific instructions if the connector is running in CloudHub (like changing the Mule Runtime version, etc)
//- The first list of steps is for in-place upgrades, probably just updating via Maven or  Anypoint Studio  and re deploying.
//- The second list is for the connectors that are older and require additional steps.
//- Some of this might not apply (i.e. a connector is backwards compatible with all released versions or there is no previous version)

////

=== Features

See link:user-manual.adoc[Thru MFT Connector User Guide]

// . <Feature_Title> - A description of the feature

//Example of a Feature listing:

//NTLM Authentication - NTLM authentication is now more robust and widely compatible with more domain controller configurations.

////
=== <Connector_Version> Fixed in this Release

- <Bug_Title> - <Conditions under which the bug used to happen, explain which was the result, which is now the fixed result>
////

//Example of a Bug listing:

//- Asyncronous processing now works when invoking via an External interface - Previously, when invoking an asyncronous service, the call could end up in a deadlock unless //lock(object) was used. Now, the connector locks automatically and you don’t need to do it.

//Example of what is NOT A BUG listing

//- Fixed CLDCONNECT-XYZ (because projects are not public)
//- Functional tests XYZ now work (because functional testing or any other part of the development process is not visible to customers)
//- Increased Sonar coverage (ditto)
//- Resolved NPE (lacking information like scenarios under which it can be reproduced, what is NPE, etc)

////
=== <Connector_Version> Known Issues

<Connector_Issues, use the same format as Bug listings>
////

=== Support Resources
////
could also be named See Also
////
* Learn how to link:https://docs.mulesoft.com/anypoint-studio/v/7.1/add-modules-in-studio-to[Install Anypoint Connectors] from Anypoint Exchange in Studio 7.
* Access MuleSoft’s MuleForge link:http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft’s link:http://www.mulesoft.com/support-login[Customer Portal].
